# Generated by Django 3.2.4 on 2021-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
