# Generated by Django 3.2.4 on 2021-11-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_main', '0002_student_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
